- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install MongoDB service
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: start & Enable mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: Replace conf file entry
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
      